name: Build and Test
on:
  push:
    branches: [ main, feature/7 ]
  pull_request:
    branches: [ main ]
jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm install    
      - name: build and test
        run: |
          npm run test
          npm run build